services:
  backend:
    build: ./backend
    image: backend-service-image
    container_name: backend_container
    ports:
      - "5000:5000"
  
  frontend:
    build: ./frontend
    image: frontend-service-image
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
