services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
  
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
