services:
  backend:
    build: ./backend
    image: yeharamewan/backend-service-image:${BUILD_NUMBER} 
    container_name: backend_container
    ports:
      - "5000:5000"
  
  frontend:
    build: ./frontend
    image: yeharamewan/frontend-service-image:${BUILD_NUMBER} 
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
